#!/usr/bin/env bash

# find all dotfiles | remove leading './' | replace newlines with spaces | trim leading and trailing spaces
folders=$(find . -maxdepth 1 -mindepth 1 -type d ! -name '.*' ! -name 'powershell' | sed 's|^\./||' | tr '\n' ' ' | awk '{$1=$1; print}')

for folder in $folders
do
    stow -D $folder
    echo "Stowing $folder"
    stow $folder
done
