#!/usr/bin/env bash

folders=$(
    find . -maxdepth 1 -mindepth 1 -type d ! -name '.*' ! -name 'powershell' \
    | sed 's|^\./||' \     # Remove leading './'
    | tr '\n' ' ' \        # Replace newlines with spaces 
    | awk '{$1=$1; print}' # Trim leading and trailing spaces
)

for folder in $folders
do
    stow -D $folder
    stow $folder
done
