#!/usr/bin/env bash

folders=$(find . -maxdepth 1 -mindepth 1 -type d ! -name '.*' | sed 's|^\./||' | tr '\n' ' ' | awk '{$1=$1; print}')

for folder in $folders
do
    stow -D $folder
    stow $folder
done
