gui:
  # If true, show a random tip in the command log when Lazygit starts
  showRandomTip: false

  # Nerd fonts version to use.
  # One of: '2' | '3' | empty string (default)
  # If empty, do not show icons.
  nerdFontsVersion: "3"

  # Length of commit hash in commits view. 0 shows '*' if NF icons aren't on.
  commitHashLength: 5

  # If true, show commit hashes alongside branch names in the branches view.
  showBranchCommitHash: true

  # Height of the command log view
  commandLogSize: 4

  # How things are filtered when typing '/'.
  # One of 'substring' (default) | 'fuzzy'
  filterMode: fuzzy

# Config relating to git
git:
  # If true, parse emoji strings in commit messages e.g. render :rocket: as 🚀
  # (This should really be under 'gui', not 'git')
  parseEmoji: true

os:
  editPreset: nvim
